baseURL = 'https://eleoletras.github.io/'
languageCode = 'es-ar'
title = 'eLeoLetras'
theme = 'PaperMod'

[pagination]
pagerSize = 5

[params]
defaultTheme = "dark"
ShowReadingTime = true
ShowPostNavLinks = true
ShowBreadCrumbs = true

[menu]

  [[menu.main]]
  identifier = "cortos"
  name = "Cortos"
  url = "/cortos/"
  weight = 1

  [[menu.main]]
  identifier = "cuentos"
  name = "Cuentos"
  url = "/cuentos/"
  weight = 2

  [[menu.main]]
  identifier = "novelas"
  name = "Novelas"
  url = "/novelas/"
  weight = 3
