baseURL = 'https://eleoletras.github.io/'
languageCode = 'es-ar'
title = 'eLeoLetras'
theme = 'PaperMod'

[pagination]
pagerSize = 10

[params]
mainSections = ["cortos", "cuentos", "novelas"]
defaultTheme = "dark"
ShowReadingTime = false
ShowWordCount = false
ShowPostNavLinks = true
ShowBreadCrumbs = true

[menu]

  [[menu.main]]
  identifier = "cortos"
  name = "Cortos"
  url = "/cortos/"
  weight = 1

  [[menu.main]]
  identifier = "cuentos"
  name = "Cuentos"
  url = "/cuentos/"
  weight = 2

  [[menu.main]]
  identifier = "novelas"
  name = "Novelas"
  url = "/novelas/"
  weight = 3
